### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WilliamSouza** [jasonkack/infodocsis#9]
Any idea?
I can't get past this error:

```/infodocsis-master$ python3 infodocsis.py 10.44.133.254
Traceback (most recent call last):
  File "infodocsis.py", line 26, in <module>
    load("DOCS-PNM-MIB")
  File "/usr/lib/python3/dist-packages/snimpy/manager.py", line 580, in load
    m = mib.load(mibname)
  File "/usr/lib/python3/dist-packages/snimpy/mib.py", line 659, in load
    "{0} contains major SMI error ({1})".format(mib, details))
snimpy.mib.SMIException: b'DOCS-PNM-MIB' contains major SMI error (b'/usr/share/snmp/mibs/DOCS-PNM-MIB':5230: b"illegal base type `DsOfdmModulationType' in index element `docsPnmCmtsOptMerThreshCfgModOrder' of row docsPnmCmtsOptMerThreshCfgEntry": check with smilint -s -l1)```

**Comment by jasonkack** [comment]
Looks like a mob error. Do you have the latest mib versionSent from my Bell Samsung device over Canada's largest network.
-------- Original message --------From: zerowill <notifications@github.com> Date: 2020-07-08  2:55 p.m.  (GMT-05:00) To: jasonkack/infodocsis <infodocsis@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [jasonkack/infodocsis] Error (#9) 
Any idea?
I can't get past this error:
Traceback (most recent call last):
  File "infodocsis.py", line 26, in <module>
    load("DOCS-PNM-MIB")
  File "/usr/lib/python3/dist-packages/snimpy/manager.py", line 580, in load
    m = mib.load(mibname)
  File "/usr/lib/python3/dist-packages/snimpy/mib.py", line 659, in load
    "{0} contains major SMI error ({1})".format(mib, details))
snimpy.mib.SMIException: b'DOCS-PNM-MIB' contains major SMI error (b'/usr/share/snmp/mibs/DOCS-PNM-MIB':5230: b"illegal base type `DsOfdmModulationType' in index element `docsPnmCmtsOptMerThreshCfgModOrder' of row docsPnmCmtsOptMerThreshCfgEntry": check with smilint -s -l1)```


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jasonkack/infodocsis/issues/9",
"url": "https://github.com/jasonkack/infodocsis/issues/9",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by WilliamSouza** [comment]
A mib was wrong, thanks!
